### ISSUE TITLE
NO COMMENTS

### ISSUE THREAD

**Issue by RomBecker** [stavgn/PainterTurbo1000#3]
https://github.com/stavgn/PainterTurbo1000/blob/dd4b61c65c3c9f102ed596a4439c791872250ede/public/js/controls.js#L3

There are no comments anywhere, wtf is c in r,b,g,c

**Comment by RomBecker** [comment]
ok... so c is color..... bad var names.
what's the problem with (r,g,b, color) or (red, green, blue, color) if anyway you do

this.ranges = {
		red: r,
		green: g,
		blue: b
	};

and can be shortened with object litteral

**Comment by stavgn** [comment]
done
